title:            Gauna Code
description:      Where software, DevOps, and infrastructure come together.
disqus_shortname: gaunacode
reading_time:     true
words_per_minute: 150
url: https://gaunacode.netlify.com # When testing locally leave blank or use http://localhost:4000

## => Owner/author information
##############################
owner:
  name:           Facundo Gauna
  avatar:         headshot.jpg
  bio:            "🥑Avocado Eater | Lover of Nanoservices"
  email:          
  twitter:        gaunacode
  facebook:       
  github:         fgauna12
  stackexchange:  
  linkedin:       facundo-gauna-601b8a47
  instagram:      
  flickr:         
  tumblr:         
  google_plus: # +mmistakes

## => Background
##############################
# Background image to be tiled on all pages
background: 

## => Analytics
##############################
google_analytics:   UA-80721031-1
google_verify:      # get this from your webmaster console
bing_verify:        # https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here

## => Post
##############################
## excerpt
excerpt_separator: <!-- more -->

## => Paginate
##############################
paginate: 5 # Amount of post to show on home page

## => Markdown Enhancements
##############################
## Mathjax
mathjax: # false (default), true
mathjax_autoNumber: # false (default), true

## Mermaid
mermaid: # false (default), true

## Chart
chart: # false (default), true

## => CDN Source
##############################
sources: unpkg

## => Build
##############################
timezone:    America/New_York
future:      false  # publish future dated posts?
permalink:   /:categories/:title/

highlighter: rouge
markdown: kramdown

kramdown:
  input: GFM
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

sass:
  sass_dir: _sass
  style: compressed

include: 
  - .htaccess
  - _pages
exclude: 
  - "*.less"
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - config
  - gulpfile.js
  - lib
  - log
  - node_modules
  - package.json
  - spec
  - tmp

## => Plugins
##############################
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-gist
  - jekyll-feed
  - jemoji
