# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Gauna Code
myname: Facundo Gauna
email: hello@gaunacode.com
description: > # this means to ignore newlines until "baseurl:"
  My adventures in all things development. That being in .NET, AngularJS, NoSQL, and Azure
baseurl: "" # the subpath of your site, e.g. /blog
#url: "http://fgauna12.github.io" # the base hostname & protocol for your site
url: "http://localhost:4000"
#twitter_username: fgauna12
github_username:  fgauna12
linkedin_profile: www.linkedin.com/in/facundo-gauna-601b8a47

# Build settings
markdown: kramdown
