# Site setings
name: 'GaunaCode'
description: "Hello, I'm Facundo Gauna. I help teams build cloud-native apps on Azure."
meta_description: ''
logo: 'assets/images/GaunaLogo.png'
favicon: 'assets/favicon/favicon.ico'
baseurl: 
production_url: https://gunnacode.netlify.app/
#disqus: 'GaunaCode'
#mailchimp_url: 'https://gmail.us20.list-manage.com/subscribe/post?u=c3b64d95e96a96aad7ceabf79&amp;id=d425788096'
cover_image: trimmed-juan-pablo-daniel-MvNfMRw3I5k-unsplash.jpg
# Add your GA Tracking Id
ga_analytics: UA-80721031-1

url: "https://gaunacode.com" # the base hostname & protocol for your site
plugins:
  - jekyll-sitemap

# Author
author:
  name: 'Facundo Gauna'
  short_name: 'Facundo'
  image: 'myface.jpg'
  greetings: 'Facundo Gauna'
  description: 'Building <a target="_blank" href="https://docs.microsoft.com/en-us/dotnet/architecture/cloud-native/definition">cloud-native</a> apps on Azure'
  bio: 'Facundo is Solutions Architect at BoxBoat. He specializes in building cloud-native apps on Azure.'
# Contact form setings
email: 
contact_page_description: ""
thankyou_page_description: ""

# Social links
twitter: 'gaunacode'
github: 'fgauna12'
linkedin: 'facundo-gauna-601b8a47'
rsslink: 'https://gaunacode.com/feed.xml'

# Navigation
navigation:
  - text: About
    url: /about/

# Required Plugins
plugins_dir:
  - jekyll-paginate
  - jekyll-tagsgenerator
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji

# Pagination
paginate: 5
paginate_path: /page:num/

# Permalinks
permalink: /:title

# Other
markdown: kramdown
highlighter: rouge

# Markdown Processors
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

# Sass
sass:
  sass_dir: _sass
  style: compressed
