# Site setings
name: 'Facundo'
description: "Hello, I'm Facundo. I'm a Cloud Solutions Architect at New Signature. I help companies deliver more through Azure, DevOps, and architecture. Above all, I push towards using technology to innovate and create business value."
meta_description: ''
logo: 'assets/images/GaunaLogo.png'
favicon: 'assets/favicon/favicon.ico'
baseurl: 
production_url: https://fgauna12.github.io
disqus: 'GaunaCode'
mailchimp_url: 'https://gmail.us20.list-manage.com/subscribe/post?u=c3b64d95e96a96aad7ceabf79&amp;id=d425788096'
cover_image: bc_1.jpg
# Add your GA Tracking Id
ga_analytics: UA-80721031-1


# Author
author:
  name: 'Facundo Gauna'
  image: 'myface.jpg'
  greetings: 'Facundo Gauna'
  description: "Cloud. DevOps. Architecture"
  bio: 'Facundo is Cloud Solutions Architect at Nebbia Technology. He helps companies get unstuck when delivering software due to processes or unproductive architectures.'
# Contact form setings
email: hello@gaunacode.com
contact_page_description: "Horace theme comes with a contact form built-in. You can use this form with Formspree service and get up to 50 submissions for free. Also, you can easily switch to another service if you want."
thankyou_page_description: "Your message has been successfully sent. I will contact you very soon!"

# Social links
twitter: 'gaunacode'
github: 'fgauna12'
linkedin: 'facundo-gauna-601b8a47'

# Navigation
navigation:
  - text: About
    url: /about/

# Required Plugins
plugins_dir:
  - jekyll-paginate
  - jekyll-tagsgenerator
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji

# Pagination
paginate: 5
paginate_path: /page:num/

# Permalinks
permalink: /:title

# Other
markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: compressed
